// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7zdbC_kUoSzHJKFTYAqRvUUqRWz9szX8',
    appId: '1:890275161522:web:62e16b0a34c4a64362b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    authDomain: 'fir-c8bc9.firebaseapp.com',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    measurementId: 'G-Q1VFFPKMRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnNfkFboSG9gQhaLk-i5nqaMhHgsHLX9o',
    appId: '1:890275161522:android:0874ed3053ae1c1b62b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUcWL8L9OrLglfU042gmpJ84sgAcok0c',
    appId: '1:890275161522:ios:575d2561e2d3d21a62b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUcWL8L9OrLglfU042gmpJ84sgAcok0c',
    appId: '1:890275161522:ios:575d2561e2d3d21a62b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    iosBundleId: 'com.example.feedbackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7zdbC_kUoSzHJKFTYAqRvUUqRWz9szX8',
    appId: '1:890275161522:web:a400303d3ed2e5c762b0ab',
    messagingSenderId: '890275161522',
    projectId: 'fir-c8bc9',
    authDomain: 'fir-c8bc9.firebaseapp.com',
    storageBucket: 'fir-c8bc9.firebasestorage.app',
    measurementId: 'G-WR2TG9MNTD',
  );
}
